[hello] 
  other = "Hello From Service API"

[Notfound-Error]
  other = "{{.Method}} cho {{.Route}} is not supported"

[Unauthorized-Error] 
  other = "You are not authorized to perform following operation"

[Internal-Error] 
  other = "Internal error , please try again"

[Badrequest-Error] 
  other = "{{.Reason}}"

[Notallowed-Error] 
  other = "Method {{.Method}} for {{.Route}} is not allowed" 

[required] 
  other = "is required"



