[hello] 
  other = "Xin chao tu Service API"

[Notfound-Error]
  other = "trường {{.Method}} cho {{.Route}} không được hỗ trợ"


[Unauthorized-Error] 
  other = "bạn không được phép thực hiện thao tác này"

[Internal-Error] 
  other = "lỗi máy chủ nội bộ, vui lòng thử lại sau"

[Badrequest-Error] 
  other = "{{.Reason}}"

[Notallowed-Error] 
  other = "Method {{.Method}} cho {{.Route}} khong duoc phep" 

[required] 
  other = "la truong bat buoc"

